name: Server B

on:
  push: 
    tags:
      - 'v\d+\.\d+\.\d+'
      - 'v[0-9]{8}-[0-9]{4}' 
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Testing
        run: echo "Building Server B"